// mksyscall.pl mount_openbsd.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package syscallx

import "syscall"

import "unsafe"

// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func mount(tpe string, dir string, flags int, data uintptr) (err error) {
	var _p0 *byte
	_p0, err = syscall.BytePtrFromString(tpe)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = syscall.BytePtrFromString(dir)
	if err != nil {
		return
	}
	_, _, e1 := syscall.Syscall6(syscall.SYS_MOUNT, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), uintptr(flags), uintptr(data), 0, 0)
	use(unsafe.Pointer(_p0))
	use(unsafe.Pointer(_p1))
	if e1 != 0 {
		err = e1
	}
	return
}
